### ISSUE TITLE
Please add new method `wait_for_element_show()`

### ISSUE THREAD

**Issue by vimagick** [horejsek/python-webdriverwrapper#11]
Common usecase: Click something, then wait for another hidden thing to show.
😄

**Comment by horejsek** [comment]
That method already exists as [`wait_for_element`](http://horejsek.github.io/python-webdriverwrapper/#webdriverwrapper.wrapper._WebdriverWrapper.wait_for_element) which also returns that element. So when you want to click on something and than wait for something else, you can do that as:

    driver.click('button')
    elm = driver.wait_for_element(tag_name='form')

Or do you mean something else?

**Comment by vimagick** [comment]
Does it return hidden elements?

**Comment by horejsek** [comment]
I see what you mean. `wait_for_element` waits for any element whether you need similar method as `wait_for_element_hide` which handles both hidden and removed elements. Ok, it can be done.

**Comment by vimagick** [comment]
Great ! You are awesome 👍

**Comment by horejsek** [comment]
Fixed in version 2.5.0. It's not new method but I changed behavior of current method so `wait_for_element` now waits only for visible elements. I can't see any reasonable use case to wait for hidden elements in several years of testing by Selenium.

**Comment by vimagick** [comment]
The original `wait_for_element()` is useful. For example, I can check a element is present in source code which maybe not visible until mouse hover.

**Comment by horejsek** [comment]
Hmm. In that case I suggest to add `wait_for_hidden_element`. It will be more clear I think.

**Comment by vimagick** [comment]
Hi. These 3 methods will cover all situations:

- `wait_for_element()` for element (regardless of visibility)
- `wait_for_element_hide()` for element (becomes hidden or disappeared)
- `wait_for_element_show()` for element (becomes visible)

I'm still using the old version (2.3.0). Thank you a lot.

**Comment by horejsek** [comment]
I merged your request, updated doc and release version 2.6.0.
